[project]
name = "mi-study"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "captum>=0.8.0",
    "gymnasium>=1.2.1",
    "matplotlib>=3.10.7",
    "numpy>=1.26.4",
    "torch>=2.9.0",
]
